version: "1.0"
services:
  backend:
    build: ./backend
    env_file:
      - ./backend/.env
    ports:
      - "8001:8000"
  frontend:
    build: ./frontend
    ports:
      - "5000:5000"